### ISSUE TITLE
Doesn't work with Python 3.7

### ISSUE THREAD

**Issue by slavkoja** [kgaughan/dovecotauth#5]
You have marked it as work with Python 3, but i got some errors with Python 3.7:

+ by default unix socket file is read-only
+ dict hasn't iteritems()
+ base64... requires bytes

I got it working with these changes:
```patch
--- dovecotauth.py.bak	2019-01-27 17:45:18.996892541 +0100
+++ dovecotauth.py	2019-01-27 17:47:42.084990114 +0100
@@ -62,7 +62,7 @@
     if inet:
         sock = socket.create_connection(inet)
     try:
-        yield Protocol(service, sock.makefile())
+        yield Protocol(service, sock.makefile("rw"))
     finally:
         sock.shutdown(socket.SHUT_RDWR)
         sock.close()
@@ -193,7 +193,7 @@
                 del kwargs[prohibited]
 
         args = ["{}={}".format(key, value)
-                for key, value in kwargs.iteritems()]
+                for key, value in kwargs.items()]
 
         for flag, name in ((secured, 'secured'),
                            (valid_client_cert, 'valid-client-cert'),
@@ -201,8 +201,8 @@
             if flag:
                 args.append(name)
 
-        resp = self._SUPPORTED[mechanism](uname, pwd)
-        args.append('resp=' + base64.b64encode(resp))
+        resp = _SUPPORTED[mechanism](uname, pwd)
+        args.append('resp=' + base64.b64encode(resp.encode()).decode())
 
         self.fh.write("AUTH\t{}\t{}\tservice={}\t{}\n".format(self.req_id,
                                                               mechanism,
```

**Comment by kgaughan** [comment]
It does now. I was part of the way through getting it to work with Python 3, but hadn't gotten around to finishing it. The most recent HEAD works just fine.

**Comment by kgaughan** [comment]
While I've closed the issue, I haven't made a release yet, so if you want to do any testing, feel free! The library also now includes a simple server daemon to demonstrate it. I need to do some cleanup of the code, and add some documentation still.

**Comment by slavkoja** [comment]
I will try/check it of course, thanks ;-)

**Comment by kgaughan** [comment]
I pushed up some additional fixes last night for Python 3, and some rough docs.

**Comment by slavkoja** [comment]
I have no free time in these days, but perhaps you will be interested in my debian's package, you can see it at https://debs.slavino.sk/pool/main/d/dovecotauth/ -- the version number is latest commit date used, as you didn't real release yet ;-)

**Comment by slavkoja** [comment]
OK, i tried it. I tried all combinations -- the valid credentials, invalid password and invalid user and all seems to work as expected with python 3.7 ;-)

Can you please do release (tag)?

**Comment by kgaughan** [comment]
Sure! I'm using it in a production (well, as much as one's own servers can be called 'production') environment too, and I haven't ran into any issues. I'll look into doing a release a little later.

**Comment by kgaughan** [comment]
Done! I had to release it as 1.0.1 due to messing up some of the flit configuration.

**Comment by slavkoja** [comment]
Hmm, switching to flit breaks packaging for debian, because flit is not available in it...

**Comment by kgaughan** [comment]
Can you build from the wheel instead?
